name: Build & Publish

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.SECRET_GITHUB_USER }}
      NUGET_PAT: ${{ secrets.SECRET_NUGET_PAT }}
    steps:
    - uses: actions/checkout@v2
    - name: Download main application
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.Web.Application
        path: Extensions/Application
        repo: realtorist/Realtorist.Web.Application
    - name: Download admin application
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.Web.Admin.Application
        path: Extensions/Admin
        repo: realtorist/Realtorist.Web.Admin.Application
    - name: Download theme
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.Web.Themes.Default
        path: Extensions/Theme
        repo: realtorist/Realtorist.Web.Themes.Default
    - name: Download LetsEncrypt
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.Web.LetsEncrypt
        path: Extensions/LetsEncrypt
        repo: realtorist/Realtorist.Web.LetsEncrypt
    - name: Download services
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.Services.Implementations.Default
        path: Extensions/Services
        repo: realtorist/Realtorist.Services.Implementations.Default
    - name: Download data access
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.DataAccess.Implementations.Mongo
        path: Extensions/MongoDataAccess
        repo: realtorist/Realtorist.DataAccess.Implementations.Mongo
    - name: Download geo coding
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.GeoCoding.Implementations.Here
        path: Extensions/HereGeoCoding
        repo: realtorist/Realtorist.GeoCoding.Implementations.Here
    - name: Download CREA DDF
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: publish.yml
        branch: master
        event: push
        name: Realtorist.RetsClient.Implementations.Crea
        path: Extensions/CREA
        repo: Realtorist.RetsClient.Implementations.Crea
    - name: Build docker image
      run: docker-compose build
    - name: Tag docker image version
      run: docker tag ghcr.io/realtorist/realtorist:latest ghcr.io/realtorist/realtorist:$GITHUB_RUN_NUMBER
    - name: Tag docker image version for Docker hub
      run: docker tag ghcr.io/realtorist/realtorist:latest dbondarchuk/realtorist:$GITHUB_RUN_NUMBER
    - name: Tag docker image latest for Docker hub
      run: docker tag ghcr.io/realtorist/realtorist:latest dbondarchuk/realtorist:latest
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to the Docker hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.SECRET_DOCKER_USERNAME }}
        password: ${{ secrets.SECRET_DOCKER_TOKEN }}
    - name: Push image (latest) - ghcr
      run: docker push ghcr.io/realtorist/realtorist:latest
    - name: Push image (version) - ghcr
      run: docker push ghcr.io/realtorist/realtorist:$GITHUB_RUN_NUMBER
    - name: Push image (latest) - Docker hub
      run: docker push dbondarchuk/realtorist:latest
    - name: Push image (version) - Docker hub
      run: docker push dbondarchuk/realtorist:$GITHUB_RUN_NUMBER
